server:
  port: 7778

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/customer
    username: root
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/crypto
          jwk-set-uri: http://localhost:8080/realms/crypto/protocol/openid-connect/certs

logging:
  level:
    root : debug
    org.springframework.web : info

