server:
  port: 7777

spring:
  r2dbc.url: r2dbc:mariadb://localhost/cashwallet
  r2dbc.username: root
  r2dbc.password:
  security:
    oauth2:
      resourceserver:
         jwt:
          issuer-uri: http://localhost:8080/realms/crypto
          jwk-set-uri: http://localhost:8080/realms/crypto/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: choice-bird-13111-us1-kafka.upstash.io:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="Y2hvaWNlLWJpcmQtMTMxMTEkWe2x-j9DaWJuXOFr0sJIntSo8VQNxiik1Iqt02s" password="93332225454647ed831daac66e993873";



logging:
  level:
    root : debug
    org.springframework.web : info

